return Def.ActorFrame{
	LoadFont("_credit")..{
		Text=' \n\n \n\nYoshihiko Ota\n\n \n\nYasumi Takase\n\n \n\nKota Wakasa\n\nTaquashi Nishibori\nManabu Hazama\nNorio Suzuki\nKozo Murotani\nTakenobu Fujishima\nTakeshi Komiya\nKidai Suzuki\nNaohiro Yamamoto\nKazuyasu Kawamura\nTakayuki Ito\nYuma Miyazaki\nAtsushi Suwa\n\n \n\nShinichirou Hashimoto\n\nYuki Shinpo\nYoshiko Ichijo\nYumi Yoshida\nKeiko Sato\nShingo Hikiami\nTakashi Kinbara\nMichiyo Oshio\n\n \n\nMai Kitazawa\n\n \n\nNAOKI MAEDA\n\n \n\nStillwind Borenstein\n\n \n\nYasuhiro Taguchi\n\n \n\njun\n\n \n\nDKC Crew\nAkira Ishihara\nHarmony Machine\nJena Rose\nSystem 7\nBill Hamel\nwolli\nOR-IF-IS\nRuffage & Size\nDarwin\nDDT\nTommie Sunshine\nKoutaro Satou\nMakoto Shimoyama\n\n \n\nAtsushi Kondo\n\n \n\nHideaki Shikama\n\n \n\nEiichi Yokoyama\nYoshihide Ozaki\nMasashi Yamaki\nToshihiro Kondo\nWan Xin\nAzusa Hiratsuka\nHiromi Yoshioka\nHideyuki Sakurai\nMunehiro Yoshida\n\n \n\n \n\nLi Jun\n\n \n\nLi Yueqiang\nSun Wenhao\nWang Xi\nLu Bin\n\n \n\nYe Lina\nYing Kai\nZhu Wenyi\nChen Xiaoping\n\n \n\nYMKC\nKevin Mitchell\nAldrin Jayson Nicolas\nJoseph Eder\nRyan Iyengar\nBryant Kongkachandra\nBrian Perez\n\n \n\nWil-Dog and Justin from Ozomatli\n\n \n\nAll other DanceDanceRevolution Teams\n  and Bemani Staff\n\nTakashi Umeda\nU1-ASAMi\nToshitaka Izumida\nOsamu Fukushima\nKazuya Maruyama\nNIPPON SHONEN\ndj TAKA\nRyu☆\nTOMOSUKE\nLIVE NATION STUDIOS\nHisayuki Nakayama(Dolby Japan)\nYukako Hamaguchi\nYukata Takeda\nIzumi Sugawara\nMichael Rajna\nKazuya Takahashi\nHideaki Takahashi\nalo\nTaiyo Yamamoto\nSwaniko\nChinese Master\nOTAS\nShinichiro Matsuda\nNippori\nBabs Oikawa\nEri Kamijo\nAkira Sugiyama\nTetsuya Kobayashi\nKatsunori Kondo\nEiko Watanabe\nTakayuki Muranaka\nMakiko Kubo\nShingo Kagaya\nEtsuko Shimada\nTaku Shudo\nKenrou Shimizu\nRyo Sugawara\nNagisa Nakamoto\nAkiko Utashiro\nMariko Omori\nToshikazu Nomura\nAya Izumi\nHiroyuki Warita\nAkiko Ono\nTACOS NAOMI\nVeeton\nTakahiko Daijo\nTakuya Aono\nYasunari Aizawa\nHiroyuki Takada\nSatoshi Ueda\nTadashi Kadohori\nSatoru Yoshida\nTomoyuki Ishizu\nKazuki Takahashi\nKoji Enomoto\nSatoshi Joko\nKensaku Yoshida\nYukie Tahara\nYukie Nakanishi\nMika Sudo\nKie Watanabe\nManami Miyazaki\nMakiko Ota\nKoji Makino\nTakeshi Jonishi\nGyo Eguchi\nTakuya Kobayashi\nYuei Uematsu\nMiho Toyoda\nHirofumi Mamitsu\nTomoko Morinaga\nSaika Oga\nSayuri Sakashita\nMaya Kanno\nRui Naito\nHoriyuki Chiwata\nRyota Nozaki\nJunichi Igarashi\nAtsushi Inomata\nHidaki Chosokaba\nMaho Kawakami\nFutoshi Kashiwagi\nAyano Nishizawa\nYasushi Kawasaki\nYukio Shiono\nKazunobu Uehara\n\nand  "YOU"';
		OnCommand=cmd(horizalign,left;vertalign,top);
	};
	LoadFont("_credit")..{
		Text='<Konami Digital Entertainment Co., Ltd.>\n\nEXECUTIVE PRODUCER\n\n \n\nDIRECTOR\n\n \n\nPROGRAMMER\n\n \n\n \n \n \n \n \n \n \n \n \n \n \n \n\nDESIGNER\n\n \n\n \n \n \n \n \n \n \n\nLOGO DESIGNER\n\n \n\nSOUND PRODUCER\n\n \n\nSOUND DIRECTOR\n\n \n\nSOUND STAFF\n\n \n\nSOUND ADVISER\n\n \n\nCOMPOSER & REMIXER\n\n \n \n \n \n \n \n \n \n \n \n \n \n \n \n\nSOUND PROGRAMMER\n\n \n\nSOUND COORDINATOR\n\n \n\n \n\n \n \n \n \n \n \n \n \n \n\n \n\n \n\n \n\n \n\n \n \n \n \n\n\n\n \n \n \n \n\n \n\n \n \n \n \n \n \n \n\n \n\n \n\n \n\n \n \n\n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n\n ';
		OnCommand=cmd(horizalign,left;vertalign,top;diffuse,color("#5A97F6"));
	};
	LoadFont("_credit")..{
		Text=' \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n \n \n \n \n \n \n \n \n \n \n \n\n \n\n \n\n \n \n \n \n \n \n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n \n \n \n \n \n \n \n \n \n \n \n \n \n\n \n\n \n\n \n\n \n\nMARKETING\n\n \n \n \n \n \n \n \n \n \n\n \n\n \n\n \n\n \n\n \n \n \n \n\n\n\n \n \n \n \n\n \n\n \n \n \n \n \n \n \n\n \n\n \n\n \n\n \n \n\n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n\n ';
		OnCommand=cmd(horizalign,left;vertalign,top;diffuse,color("#B90064"));
	};
	LoadFont("_credit")..{
	Text=' \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n \n \n \n \n \n \n \n \n \n \n \n\n \n\n \n\n \n \n \n \n \n \n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n \n \n \n \n \n \n \n \n \n \n \n \n \n\n \n\n \n\n \n\n \n\n \n\n \n \n \n \n \n \n \n \n \n\n<Konami Software Shanghai, Inc.>\n\nDIRECTOR\n\n \n\nPROGRAMMER\n\n \n \n \n \n\nDESIGNER\n\n \n \n \n \n\n \n\n \n \n \n \n \n \n \n\n \n\n \n\n \n\n \n \n\n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n\n ';
		OnCommand=cmd(horizalign,left;vertalign,top;diffuse,color("#AB9AFC"));
	};
	LoadFont("_credit")..{
	Text=' \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n \n \n \n \n \n \n \n \n \n \n \n\n \n\n \n\n \n \n \n \n \n \n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n\n \n \n \n \n \n \n \n \n \n \n \n \n \n \n\n \n\n \n\n \n\n \n\n \n\n \n \n \n \n \n \n \n \n \n\n \n\n \n\n \n\n \n\n \n \n \n \n\n \n\n \n \n \n \n\nSTEP DESIGNER\n\n \n \n \n \n \n \n \n\nVOICE NARRATION\n\n \n\nSPECIAL THANKS\n\n \n \n\n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n\n ';
		OnCommand=cmd(horizalign,left;vertalign,top;diffuse,color("#A56A03"));
	};
};