return Def.ActorFrame {
	Def.ActorFrame{
		OnCommand=cmd(x,SCREEN_CENTER_X+320);
		OffCommand=cmd(sleep,.016;accelerate,.25;addx,SCREEN_WIDTH/2+20);
		LoadActor("w01")..{
		OnCommand=cmd(y,SCREEN_CENTER_Y+201;diffusealpha,0;sleep,.595;sleep,0;diffusealpha,1);
		};
		LoadActor("w02")..{
		OnCommand=cmd(y,SCREEN_CENTER_Y+167;diffusealpha,0;sleep,.595;sleep,.023;diffusealpha,1);
		};
		LoadActor("w03")..{
		OnCommand=cmd(y,SCREEN_CENTER_Y+135;diffusealpha,0;sleep,.595;sleep,.046;diffusealpha,1);
		};
		LoadActor("w04")..{
		OnCommand=cmd(y,SCREEN_CENTER_Y+104;diffusealpha,0;sleep,.595;sleep,.069;diffusealpha,1);
		};
		LoadActor("w05")..{
		OnCommand=cmd(y,SCREEN_CENTER_Y+75;diffusealpha,0;sleep,.595;sleep,.092;diffusealpha,1);
		};
		LoadActor("w06")..{
		OnCommand=cmd(y,SCREEN_CENTER_Y+47;diffusealpha,0;sleep,.595;sleep,.115;diffusealpha,1);
		};
		LoadActor("w07")..{
		OnCommand=cmd(y,SCREEN_CENTER_Y+21;diffusealpha,0;sleep,.595;sleep,.138;diffusealpha,1);
		};
		LoadActor("w08")..{
		OnCommand=cmd(y,SCREEN_CENTER_Y-3;diffusealpha,0;sleep,.595;sleep,.161;diffusealpha,1);
		};
		LoadActor("w08")..{
		OnCommand=cmd(y,SCREEN_CENTER_Y-28;diffusealpha,0;sleep,.595;sleep,.184;diffusealpha,1);
		};
		LoadActor("w10")..{
		OnCommand=cmd(y,SCREEN_CENTER_Y-53;diffusealpha,0;sleep,.595;sleep,.207;diffusealpha,1);
		};
		LoadActor("w11")..{
		OnCommand=cmd(y,SCREEN_CENTER_Y-79;diffusealpha,0;sleep,.595;sleep,.23;diffusealpha,1);
		};
		LoadActor("w12")..{
		OnCommand=cmd(y,SCREEN_CENTER_Y-107;diffusealpha,0;sleep,.595;sleep,.253;diffusealpha,1);
		};
		LoadActor("w13")..{
		OnCommand=cmd(y,SCREEN_CENTER_Y-136;diffusealpha,0;sleep,.595;sleep,.276;diffusealpha,1);
		};
		LoadActor("w14")..{
		OnCommand=cmd(y,SCREEN_CENTER_Y-167;diffusealpha,0;sleep,.595;sleep,.299;diffusealpha,1);
		};
		LoadActor("w15")..{
		OnCommand=cmd(y,SCREEN_CENTER_Y-199;diffusealpha,0;sleep,.595;sleep,.322;diffusealpha,1);
		};
	};
	LoadActor(THEME:GetPathG("","MWHL_bg"))..{
		InitCommand=cmd(x,SCREEN_CENTER_X+235;y,SCREEN_CENTER_Y);
		OffCommand=cmd(visible,false);
	};
};