local path = "../ScreenEvaluationNormal decorations/";
return Def.ActorFrame{
	LoadActor("../_header/centered");
	LoadActor("../_footer");
	LoadActor("Announcer");
	Def.ActorFrame{
		OnCommand=cmd(x,SCREEN_CENTER_X;y,SCREEN_CENTER_Y+26;zoomy,0;linear,.2;zoomy,1);
		OffCommand=cmd(sleep,.016;linear,.3;zoomy,0);
		LoadActor(path.."judgmentBG");
		LoadActor(path.."JudgeRows");
	};
	LoadActor(path.."RaveDec");
	Def.ActorFrame{
		OnCommand=cmd(x,SCREEN_CENTER_X;y,SCREEN_CENTER_Y-133;zoomy,0;linear,.36;zoomy,1);
		OffCommand=cmd(sleep,.32;linear,.08;zoomy,0);
		LoadActor("../CommonScreen/sides")..{
			OnCommand=cmd(x,-158;y,23;);
			OffCommand=cmd(accelerate,.233;addx,-20;sleep,0;diffusealpha,0);
		};
		LoadActor("../CommonScreen/sides")..{
			OnCommand=cmd(x,158;y,23;zoomx,-1);
			OffCommand=cmd(accelerate,.233;addx,-20;sleep,0;diffusealpha,0);
		};
		LoadActor("../banner frame")..{
			OnCommand=cmd(zoomy,0;sleep,.333;decelerate,.133;zoomy,1;accelerate,.033;zoomx,1.06;decelerate,.033;zoomx,1);
		};
		LoadActor(path.."banner")..{
			OnCommand=cmd(y,0);
		};
		LoadActor("../_playmode")..{
			OnCommand=cmd(x,-107;y,43;vertalign,top;zoomy,0;diffusealpha,.8;addy,-43;sleep,.000;sleep,.333;decelerate,.133;zoomy,1;diffusealpha,1;addy,43;accelerate,.033;zoomx,1.05;addx,-9;decelerate,.033;zoomx,1;addx,9);
		};
		LoadActor("../eval_stage")..{
			OnCommand=cmd(x,22;y,54);
			Condition= not GAMESTATE:IsCourseMode();
		};
	};
	LoadActor(path.."p1_ind")..{
		OnCommand=cmd(player,PLAYER_1;x,SCREEN_CENTER_X-234;y,SCREEN_CENTER_Y-47;zoomy,0;diffusealpha,0;sleep,.24;linear,.12;zoomy,1;diffusealpha,1);
		OffCommand=cmd(zoomy,1;sleep,0;sleep,.016;linear,.1;zoomy,0);
	};
	LoadActor(path.."p2_ind")..{
		OnCommand=cmd(player,PLAYER_2;x,SCREEN_CENTER_X+248;y,SCREEN_CENTER_Y-47;zoomy,0;diffusealpha,0;sleep,.24;linear,.12;zoomy,1;diffusealpha,1);
		OffCommand=cmd(zoomy,1;sleep,0;sleep,.016;linear,.1;zoomy,0);
	};
	LoadActor("../_titles/result")..{
		OnCommand=cmd(x,SCREEN_CENTER_X-15;y,SCREEN_CENTER_Y-203;rotationz,-4;diffusealpha,0;zoom,1;addy,-12;sleep,.000;sleep,.283;decelerate,.066;diffusealpha,1;addy,12;linear,.016;zoom,1.083;decelerate,.083;zoom,1);
		OffCommand=cmd(linear,.1;addy,-14;diffusealpha,0);
	};
	LoadActor(path.."NewRecDec");
	LoadActor("statsP1")..{
		OnCommand=cmd(player,PLAYER_1;x,SCREEN_CENTER_X-72;y,SCREEN_CENTER_Y-64;diffusealpha,0;sleep,.24;diffusealpha,1);
		OffCommand=cmd(sleep,.04;diffusealpha,0);
	};
	LoadActor("statsP2")..{
		OnCommand=cmd(player,PLAYER_2;x,SCREEN_CENTER_X+131;y,SCREEN_CENTER_Y-64;diffusealpha,0;sleep,.24;diffusealpha,1);
		OffCommand=cmd(sleep,.04;diffusealpha,0);
	};
};